// Code generated by mockery v2.50.4. DO NOT EDIT.

package persistence

import (
	context "context"

	entities "github.com/jfelipearaujo-urlshortener/urlshortener-app/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// MockUrlRepository is an autogenerated mock type for the UrlRepository type
type MockUrlRepository struct {
	mock.Mock
}

type MockUrlRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUrlRepository) EXPECT() *MockUrlRepository_Expecter {
	return &MockUrlRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, url
func (_m *MockUrlRepository) Create(ctx context.Context, url *entities.Url) error {
	ret := _m.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Url) error); ok {
		r0 = rf(ctx, url)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUrlRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUrlRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - url *entities.Url
func (_e *MockUrlRepository_Expecter) Create(ctx interface{}, url interface{}) *MockUrlRepository_Create_Call {
	return &MockUrlRepository_Create_Call{Call: _e.mock.On("Create", ctx, url)}
}

func (_c *MockUrlRepository_Create_Call) Run(run func(ctx context.Context, url *entities.Url)) *MockUrlRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.Url))
	})
	return _c
}

func (_c *MockUrlRepository_Create_Call) Return(_a0 error) *MockUrlRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUrlRepository_Create_Call) RunAndReturn(run func(context.Context, *entities.Url) error) *MockUrlRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUrlRepository creates a new instance of MockUrlRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUrlRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUrlRepository {
	mock := &MockUrlRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
